# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New section
"""

import cv2 as cv
from google.colab.patches import cv_imshow
image=cv.imread("/content/abhi.jpg")
cv_imshow(image)